name: Market Alert Bot

on:
  schedule:
  - cron: '0 13 * * 1-5'   # 8:00 AM Chicago time (CDT)
  - cron: '30 16 * * 1-5'  # 11:30 AM Chicago time (CDT)
  workflow_dispatch:

jobs:
  run-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up Chrome & ChromeDriver
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Run market alert bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          MARKETAUX_API_KEY: ${{ secrets.MARKETAUX_API_KEY }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python spx_premarket_alerts.py

      - name: Commit and push updated CSV log
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/CDUS-Trading/Market-Sentiment-Alert-Bot.git

          git add market_predictions.csv
          git commit -m "📈 Update log on $(date -u)" || echo "No changes to commit"

          git pull --rebase
          git push origin HEAD:main
