name: Market Alert Bot

on:
  schedule:
    - cron: '0 6 * * 1-5'     # 6 AM UTC (weekday mornings)
    - cron: '16 16 * * 1-5'   # 12 PM EST (midday)
  workflow_dispatch:

jobs:
  run-alert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Market Alert Bot
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      run: python spx_premarket_alerts.py
