name: Market Alert Bot

on:
  schedule:
    - cron: '0 12 * * 1-5'  # 8 AM EDT (UTC-4)
    - cron: '16 16 * * 1-5' # Midday alert (12 PM EDT)
  workflow_dispatch:

jobs:
  run-alert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up Chrome & ChromeDriver
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable

    - name: Run market alert bot
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
      run: |
        echo "Checking Chrome version:"
        google-chrome --version
        echo "Launching Python script"
        python spx_premarket_alerts.py
