name: Market Alert Bot

on:
  schedule:
    - cron: '0 6 * * 1-5'    # 6 AM UTC (2 AM EDT, 1 AM EST) – adjust as needed
    - cron: '16 16 * * 1-5'  # 12 PM EDT (16:00 UTC) – Midday Alert
  workflow_dispatch:         # Allow manual run

jobs:
  run-alert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up Chrome
      id: setup-chrome
      uses: browser-actions/setup-chrome@latest

    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: ${{ steps.setup-chrome.outputs.chrome-version }}


    - name: Run market alert bot
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }} 
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      run: python spx_premarket_alerts.py
